export const DEFAULT_COMPONENT_RECIPES: Record<string, Record<string, string>> = {
  // ── Buttons ──────────────────────────────────────────────────────
  'btn': {
    display: 'inline-flex',
    'align-items': 'center',
    'justify-content': 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    'font-size': '0.875rem',
    'font-weight': '500',
    'line-height': '1.25rem',
    'border-radius': '0.5rem',
    border: '1px solid transparent',
    cursor: 'pointer',
    'transition-property': 'color, background-color, border-color, box-shadow',
    'transition-duration': '150ms',
    'transition-timing-function': 'ease-in-out',
    'box-sizing': 'border-box',
  },
  'btn-primary': {
    display: 'inline-flex',
    'align-items': 'center',
    'justify-content': 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    'font-size': '0.875rem',
    'font-weight': '600',
    'line-height': '1.25rem',
    'border-radius': '0.5rem',
    border: '1px solid transparent',
    'background-color': 'var(--bear-primary-500, #3b82f6)',
    color: '#ffffff',
    cursor: 'pointer',
    'transition-property': 'background-color, box-shadow',
    'transition-duration': '150ms',
    'box-sizing': 'border-box',
  },
  'btn-outline': {
    display: 'inline-flex',
    'align-items': 'center',
    'justify-content': 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    'font-size': '0.875rem',
    'font-weight': '500',
    'line-height': '1.25rem',
    'border-radius': '0.5rem',
    border: '1px solid #cbd5e1',
    'background-color': 'transparent',
    color: 'inherit',
    cursor: 'pointer',
    'transition-property': 'border-color, background-color',
    'transition-duration': '150ms',
    'box-sizing': 'border-box',
  },
  'btn-ghost': {
    display: 'inline-flex',
    'align-items': 'center',
    'justify-content': 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    'font-size': '0.875rem',
    'font-weight': '500',
    'line-height': '1.25rem',
    'border-radius': '0.5rem',
    border: '1px solid transparent',
    'background-color': 'transparent',
    color: 'inherit',
    cursor: 'pointer',
    'transition-property': 'background-color',
    'transition-duration': '150ms',
    'box-sizing': 'border-box',
  },
  'btn-sm': {
    padding: '0.25rem 0.75rem',
    'font-size': '0.75rem',
    'border-radius': '0.375rem',
  },
  'btn-lg': {
    padding: '0.75rem 1.5rem',
    'font-size': '1rem',
    'border-radius': '0.625rem',
  },
  'btn-icon': {
    display: 'inline-flex',
    'align-items': 'center',
    'justify-content': 'center',
    width: '2.5rem',
    height: '2.5rem',
    padding: '0',
    'border-radius': '0.5rem',
    border: '1px solid transparent',
    cursor: 'pointer',
    'box-sizing': 'border-box',
  },
  'circle-button': {
    display: 'inline-flex',
    'align-items': 'center',
    'justify-content': 'center',
    width: '2.5rem',
    height: '2.5rem',
    padding: '0',
    border: '1px solid transparent',
    'border-radius': '9999px',
    cursor: 'pointer',
    'box-sizing': 'border-box',
  },

  // ── Inputs ───────────────────────────────────────────────────────
  'input': {
    display: 'block',
    width: '100%',
    'box-sizing': 'border-box',
    padding: '0.5rem 0.75rem',
    'border-radius': '0.5rem',
    border: '1px solid #cbd5e1',
    'font-size': '0.875rem',
    'line-height': '1.5',
    'background-color': 'transparent',
    color: 'inherit',
    outline: 'none',
    'transition-property': 'border-color, box-shadow',
    'transition-duration': '150ms',
  },
  'input-rounded': {
    display: 'block',
    width: '100%',
    'box-sizing': 'border-box',
    padding: '0.5rem 0.75rem',
    'border-radius': '0.75rem',
    border: '1px solid #cbd5e1',
    'font-size': '1rem',
    'line-height': '1.5',
    'background-color': 'transparent',
    color: 'inherit',
    outline: 'none',
  },
  'input-pill': {
    display: 'block',
    width: '100%',
    'box-sizing': 'border-box',
    padding: '0.5rem 1rem',
    'border-radius': '9999px',
    border: '1px solid #cbd5e1',
    'font-size': '0.875rem',
    'line-height': '1.5',
    'background-color': 'transparent',
    color: 'inherit',
    outline: 'none',
  },
  'input-underline': {
    display: 'block',
    width: '100%',
    'box-sizing': 'border-box',
    padding: '0.5rem 0',
    border: 'none',
    'border-bottom': '2px solid #cbd5e1',
    'border-radius': '0',
    'font-size': '0.875rem',
    'line-height': '1.5',
    'background-color': 'transparent',
    color: 'inherit',
    outline: 'none',
    'transition-property': 'border-color',
    'transition-duration': '150ms',
  },
  'textarea': {
    display: 'block',
    width: '100%',
    'box-sizing': 'border-box',
    padding: '0.5rem 0.75rem',
    'border-radius': '0.5rem',
    border: '1px solid #cbd5e1',
    'font-size': '0.875rem',
    'line-height': '1.5',
    'background-color': 'transparent',
    color: 'inherit',
    outline: 'none',
    resize: 'vertical',
    'min-height': '5rem',
  },
  'select': {
    display: 'block',
    width: '100%',
    'box-sizing': 'border-box',
    padding: '0.5rem 2rem 0.5rem 0.75rem',
    'border-radius': '0.5rem',
    border: '1px solid #cbd5e1',
    'font-size': '0.875rem',
    'line-height': '1.5',
    'background-color': 'transparent',
    color: 'inherit',
    outline: 'none',
    appearance: 'none',
    cursor: 'pointer',
  },

  // ── Cards ────────────────────────────────────────────────────────
  'card': {
    'border-radius': '0.75rem',
    border: '1px solid #e2e8f0',
    'background-color': '#ffffff',
    padding: '1.5rem',
    'box-sizing': 'border-box',
  },
  'card-hover': {
    'border-radius': '0.75rem',
    border: '1px solid #e2e8f0',
    'background-color': '#ffffff',
    padding: '1.5rem',
    'box-sizing': 'border-box',
    'transition-property': 'box-shadow, border-color, transform',
    'transition-duration': '200ms',
    cursor: 'pointer',
  },
  'card-flat': {
    'border-radius': '0.75rem',
    border: 'none',
    'background-color': '#f8fafc',
    padding: '1.5rem',
    'box-sizing': 'border-box',
  },

  // ── Badges ───────────────────────────────────────────────────────
  'badge': {
    display: 'inline-flex',
    'align-items': 'center',
    padding: '0.125rem 0.625rem',
    'font-size': '0.75rem',
    'font-weight': '500',
    'line-height': '1.25rem',
    'border-radius': '9999px',
    'white-space': 'nowrap',
  },

  // ── Avatar ───────────────────────────────────────────────────────
  'avatar': {
    display: 'inline-flex',
    'align-items': 'center',
    'justify-content': 'center',
    width: '2.5rem',
    height: '2.5rem',
    'border-radius': '9999px',
    overflow: 'hidden',
    'flex-shrink': '0',
    'background-color': '#e2e8f0',
    'font-size': '0.875rem',
    'font-weight': '600',
  },
  'avatar-sm': {
    width: '2rem',
    height: '2rem',
    'font-size': '0.75rem',
  },
  'avatar-lg': {
    width: '3rem',
    height: '3rem',
    'font-size': '1rem',
  },

  // ── Divider ──────────────────────────────────────────────────────
  'divider': {
    width: '100%',
    height: '1px',
    border: 'none',
    'background-color': '#e2e8f0',
    margin: '1rem 0',
  },

  // ── Container ────────────────────────────────────────────────────
  'container': {
    width: '100%',
    'max-width': '1280px',
    'margin-left': 'auto',
    'margin-right': 'auto',
    'padding-left': '1rem',
    'padding-right': '1rem',
    'box-sizing': 'border-box',
  },

  // ── Skeleton ─────────────────────────────────────────────────────
  'skeleton': {
    'border-radius': '0.375rem',
    'background-color': '#e2e8f0',
    animation: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
  },

  // ── Prose (text content) ─────────────────────────────────────────
  'prose': {
    'max-width': '65ch',
    'line-height': '1.75',
    'font-size': '1rem',
  },

  // ── Overlay / Backdrop ───────────────────────────────────────────
  'overlay': {
    position: 'fixed',
    inset: '0',
    'background-color': 'rgba(0, 0, 0, 0.5)',
    'z-index': '40',
  },

  // ── Focus ring ───────────────────────────────────────────────────
  'focus-ring': {
    outline: '2px solid var(--bear-primary-500, #3b82f6)',
    'outline-offset': '2px',
  },

  // ── Transition presets ───────────────────────────────────────────
  'transition': {
    'transition-property': 'all',
    'transition-duration': '200ms',
    'transition-timing-function': 'ease-in-out',
  },
  'transition-fast': {
    'transition-property': 'all',
    'transition-duration': '100ms',
    'transition-timing-function': 'ease-in-out',
  },
  'transition-slow': {
    'transition-property': 'all',
    'transition-duration': '300ms',
    'transition-timing-function': 'ease-in-out',
  },
};
