export const GROUP_LABELS: Record<string, string> = {
  flex: 'Flex',
  grid: 'Grid',
  position: 'Position',
  inset: 'Inset / offsets',
  size: 'Size',
  spacing: 'Spacing',
  gap: 'Gap',
  text: 'Text',
  font: 'Font',
  list: 'List',
  display: 'Display',
  layout: 'Layout',
  overflow: 'Overflow',
  cursor: 'Cursor',
  transition: 'Transition',
  motion: 'Animation',
  transform: 'Transform',
  filter: 'Filter',
  backdrop: 'Backdrop filter',
  background: 'Background',
  outline: 'Outline',
  effect: 'Effect',
  table: 'Table',
  scroll: 'Scroll',
  interactive: 'Interactive',
  svg: 'SVG',
  a11y: 'Accessibility',
  zindex: 'Z-index',
  radius: 'Radius',
  border: 'Border',
  opacity: 'Opacity',
  shadow: 'Shadow',
  color: 'Color',
};

export const GROUP_ORDER = [
  'layout',
  'display',
  'overflow',
  'position',
  'inset',
  'zindex',
  'flex',
  'grid',
  'spacing',
  'gap',
  'size',
  'font',
  'text',
  'list',
  'color',
  'background',
  'border',
  'radius',
  'outline',
  'shadow',
  'opacity',
  'effect',
  'filter',
  'backdrop',
  'transition',
  'motion',
  'transform',
  'table',
  'scroll',
  'interactive',
  'cursor',
  'svg',
  'a11y',
] as const;

export type GroupName = (typeof GROUP_ORDER)[number];

export const PORTAL_CATEGORIES: Array<{
  id: string;
  label: string;
  groups: GroupName[];
}> = [
  { id: 'structure', label: 'Structure', groups: ['layout', 'display', 'overflow', 'zindex'] },
  { id: 'position', label: 'Position', groups: ['position', 'inset'] },
  { id: 'flex-grid', label: 'Flex & Grid', groups: ['flex', 'grid'] },
  { id: 'box-model', label: 'Box model', groups: ['spacing', 'gap'] },
  { id: 'sizing', label: 'Sizing', groups: ['size'] },
  { id: 'type', label: 'Type', groups: ['font', 'text', 'list', 'color'] },
  { id: 'surface', label: 'Surface', groups: ['background', 'border', 'radius', 'outline', 'shadow', 'opacity', 'effect'] },
  { id: 'motion', label: 'Motion', groups: ['transition', 'motion', 'transform'] },
  { id: 'fx', label: 'FX', groups: ['filter', 'backdrop'] },
  { id: 'tables', label: 'Tables', groups: ['table'] },
  { id: 'interact', label: 'Interact', groups: ['interactive', 'cursor', 'scroll'] },
  { id: 'svg', label: 'SVG', groups: ['svg'] },
  { id: 'a11y', label: 'Accessibility', groups: ['a11y'] },
];
